path = "./repos"

# --------- EXAMPLE ---------
[[service]]
application_name = "EXAMPLE"
# name of the directory where the repo will be cloned into
# $(pws)/repos/example
directory_name = "example"
url = "https://example.com"

[service.container]
name = "example"                               # optional
image = "example"
restart_policy = "example"                     # optional
ports = [["9090", "9090"], ["8080", "8080"]]   # optional
volumes = [["/", "//"], ["/", "//"]]           # optional
environment = [["KEY", "VAL"], ["KEY", "VAL"]] # optional
std_in = false                                 # optional
interactive = false                            # optional
docker_user_group_id = "1000:1000"             # optional

[service.container.build] # optional
context = "."
dockerfile = "Dockerfile"
