print_banner = true                # Enable/Disable banner at start
client = "Earth"                   # Optional
organization = "Avengers"          # Optional
configuration_file = "config.toml" # `config.toml` Default File
